### ISSUE TITLE
Implement User Interaction

### ISSUE THREAD

**Issue by Firnin** [AntonPieper/LavenderTown#18]
- [ ] ~~Basic: Enter field (eg. "C7") #19~~
- [x] Intermediate: vim-like controls to navigate #20
- [ ] Advanced: Mouse-Click Navigation #21
